# Generated by Django 5.1.6 on 2025-03-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vforce', '0001_initial'),  # Esta migración depende de la migración inicial
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',  # Nombre del modelo del cual se eliminará el campo
            name='direccion',  # Nombre del campo a eliminar
        ),
    ]