# Generated by Django 5.1.6 on 2025-03-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vforce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
